drop sequence seq_menu_id;
drop sequence seq_restaur_id;

select * from favorities;
select * from member;
select * from menu;
select * from restaurant;
select SEQ_RESTAUR_ID from menu where SEQ_RESTAUR_ID=101;

insert into menu values(SEQ_MENU_ID.nextval, ?, ?, ?, ?, ?, ?) where seq_restaur_id=?

delete menu where SEQ_RESTAUR_ID=180 and SEQ_menu_ID=1241;

--시퀀스 권한 설정 SYSYEM
grant create sequence to project;

CREATE SEQUENCE SEQ_RESTAUR_ID
START WITH 101
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_MENU_ID
START WITH 1001
INCREMENT BY 1
NOCACHE;


COMMIT;
select * from RESTAURANT;
CREATE TABLE RESTAURANT(
    SEQ_RESTAUR_ID NUMBER(3),
    RESTAUR_KIND VARCHAR2(10) NOT NULL,
    RESTAUR_NAME VARCHAR2(60) NOT NULL,
    RESTAUR_ADDRESS VARCHAR2(100) NOT NULL,
    RESTAUR_PHONE VARCHAR2(20) NOT NULL,
    RESTAUR_DELIVER VARCHAR2(1) NOT NULL,
    RESTAUR_POINT NUMBER(1) ,
    
    PRIMARY KEY (SEQ_RESTAUR_ID),
    CONSTRAINT CONS_KIND CHECK (RESTAUR_KIND IN ('한식', '중식', '일식', '양식')),
    CONSTRAINT CONS_DELIVER CHECK (RESTAUR_DELIVER IN('O', 'X')),
    CONSTRAINT CONS_POINT CHECK (RESTAUR_POINT BETWEEN 1 AND 5)
);

CREATE TABLE MENU(
    SEQ_MENU_ID NUMBER(4),
    SEQ_RESTAUR_ID NUMBER(3),
    MENU_NAME VARCHAR2(60) NOT NULL,
    MENU_PRICE INTEGER NOT NULL,
    MENU_DESC VARCHAR2(600),
    MENU_KCAL NUMBER(5),
    MENU_SOURCE VARCHAR2(300)NOT NULL,
    
    PRIMARY KEY (SEQ_MENU_ID),
    FOREIGN KEY (SEQ_RESTAUR_ID) REFERENCES RESTAURANT(SEQ_RESTAUR_ID)
);

CREATE TABLE MEMBER(
    MEMBER_ID VARCHAR2(30) NOT NULL,
    MEMBER_PASSWORD VARCHAR2(30) NOT NULL,
    MEMBER_NAME VARCHAR2(30) NOT NULL,
    MEMBER_PHONE VARCHAR2(20) NOT NULL,
    MEMBER_ADDRESS VARCHAR2(50), 
    PRIMARY KEY (MEMBER_ID)
);

CREATE TABLE FAVORITIES(
    MEMBER_ID varchar2(30),
    SEQ_RESTAUR_ID number(3),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
    FOREIGN KEY (SEQ_RESTAUR_ID) REFERENCES RESTAURANT(SEQ_RESTAUR_ID),
    PRIMARY KEY (MEMBER_ID,SEQ_RESTAUR_ID)
);

COMMIT;

select * from menu;

------------------------------------------    
--샘플 맛집데이터
------------------------------------------
--행 1
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'한식','대가','강남구 봉은사로 4길 24','02-5672379','X',NULL);
--행 2
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'한식','오통영','강남구 선릉로 158길 10','02-544-2377','X',NULL);
--행 3
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'한식','옹달샘','마포구 양화로6길 99','02-333-2440','X',NULL);
--행 4
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'한식','초당할머니순두부','강릉시 초당순두부길 77','033-652-2058','X',NULL);
--행 5
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'한식','뜨락','강남구 영동대로 142길 13-3','02-543-2987','X',NULL);
--행 6
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'한식','옛날집','강남구 선릉로 148길 38','02-549-7888','X',NULL);
--행 7
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'한식','우진해장국','제주시 서사로 11','064-757-3393','X',NULL);
--행 8
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'한식','목향원','남양주시 덕릉로 1071번길 34-11','031-527-2255','X',NULL);
--행 9
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'한식','한국집','전주시 완산구 어진길 119','063-284-2224','X',NULL);
--행 10
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'한식','해운대소문난소갈비','해운대구 중동2길 10번길 32-10','051-746-0033','X',NULL);
--행 11
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'한식','오가닉','대구 중구 중앙대로 406-9','053-424-7879','O',NULL);
--행 12
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'한식','형제추어탕','종로구 평창동 281-1','02-443-2121','O',NULL);
--행 13
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'한식','용금옥','중구 다동길 24-2','02-435-9898','O',NULL);
--행 14
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'한식','명동할매낙지','중구 명동2가 37-1','02-431-6667','O',NULL);
--행 15
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'한식','오장동 함흥냉면','중구 마른내로 108','02-303-4321','O',NULL);
--행 16
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'한식','고려삼계탕','중구 서소문로11길 1','02 987-2431','O',NULL);
--행 17
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'한식','함흥곰보냉면','종로구 창경궁로 109','02-432-3399','O',NULL);
--행 18
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'한식','기장곰장어','부산광역시 기장읍 기장해안로 70','051-765-9873','O',NULL);
--행 19
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'한식','동래할매파전','부산광역시 동래구 명륜로94번길 43-10','051-432-8765','O',NULL);
--행 20
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'한식','송정삼대국밥','부산광역시 부산진구 서면로68번길 29','051-234-5678','O',NULL);
--행 21
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'일식','토끼정 분당서현','경기 성남시 분당구 황새울로 315','031-707-3997','X',NULL);
--행 22
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'일식','삿뽀로 판교점','경기 성남시 분당구 대왕판교로606번길 58','031-8016-5990','X',NULL);
--행 23
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'일식','긴자 판교점','경기 성남시 분당구 판교로 185, 3층','031-702-9461','X',NULL);
--행 24
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'일식','도원참치','경기 성남시 분당구 판교역로192번길 14-2, 2층','031-8016-4588','O',NULL);
--행 25
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'일식','하나스시','경기 성남시 분당구 판교역로 240, 삼환하이팩스 A동 208호','031-696-1795','X',NULL);
--행 26
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'일식','시월애봄','경기 성남시 분당구 동판교로177번길 25','010-6799-1620','X',NULL);
--행 27
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'일식','CORNER111','경기 성남시 분당구 판교로319번길 13, 디테라스111호','031-606-2111','O',NULL);
--행 28
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'일식','하코야 판교아브뉴프랑점','경기 성남시 분당구 분당내곡로 151, 판교 호반 써밋 플레이스','031-705-0337','X',NULL);
--행 29
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'일식','키라메쿠 코도모','경기 성남시 분당구 판교역로146번길 20, 현대백화점 지하1층','031-708-0375','X',NULL);
--행 30
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'일식','일상화식','경기 성남시 분당구 대왕판교로 670, 유스페이스2 B동 2층 226호','010-8359-5615','X',NULL);
--행 31
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'일식','이꾸 판교점','경기 성남시 분당구 판교역로 231, 에이치스퀘어 에스동','031-789-3633','X',NULL);
--행 32
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'일식','유노추보 현대백화점판교점','경기 성남시 분당구 판교역로146번길 20','031-5170-1053','X',NULL);
--행 33
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'일식','분당구 상록면','경기 성남시 분당구 대왕판교로 660, 유스페이스1','031-628-4242','X',NULL);
--행 34
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'일식','우에노야부멘야','경기 성남시 분당구 운중로225번길 48-9','070-4219-5750','X',NULL);
--행 35
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'일식','매드피셔맨','경기 성남시 분당구 대왕판교로 660,유스페이스1 A동 지하1층 128-2호','031-724-2518','X',NULL);
--행 36
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'일식','하치 돈부리','경기 성남시 분당구 분당로53번길 14, 서현프라자','031-8017-7412','X',NULL);
--행 37
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'일식','오후정 분당서현점','경기 성남시 분당구 황새울로 337, 웰빙프라자','031-709-1282','X',NULL);
--행 38
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'일식','야타이혼텐','경기 성남시 분당구 황새울로360번길 24, 대명코아','031-701-7779','X',NULL);
--행 39
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'일식','돈돈정 서현점','경기 성남시 분당구 황새울로 337, 웰빙프라자 1층','031-705-0418','X',NULL);
--행 40
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'일식','후쿠오카모츠나베 분당점','경기 성남시 분당구 서현로180번길 19, 비전월드빌딩 1층','031-707-5553','X',NULL);
--행 41
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'중식','송화양꼬치','경기 성남시 분당구 장미로100번길 15-11','031-707-7826','X',NULL);
--행 42
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'중식','이가네양꼬치 분당판교','경기 성남시 분당구 분당내곡로 155','031-8017-9688','X',NULL);
--행 43
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'중식','차알','경기 성남시 분당구 판교역로 145','031-701-7679','X',NULL);
--행 44
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'중식','청담','경기 성남시 분당구 미금로33번길 10','031-715-7860','X',NULL);
--행 45
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'중식','중국성','경기 성남시 분당구 판교로 700 304-2호','031-708-2001','O',NULL);
--행 46
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'중식','호접몽','경기 성남시 분당구 정자일로 120','031-726-0099','X',NULL);
--행 47
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'중식','동방불패 분당서현','경기 성남시 분당구 서현로210번길 17','031-709-1131','X',NULL);
--행 48
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'중식','중화루','경기 성남시 분당구 중앙공원로40번길 8','031-701-8989','O',NULL);
--행 49
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'중식','베이징스토리','경기 성남시 분당구 판교역로 230','031-696-0306','X',NULL);
--행 50
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'중식','진궁','경기 성남시 분당구 운중로125번길 3-5','031-8016-8181','X',NULL);
--행 51
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'중식','아성중국집','경기 성남시 분당구 운중로225번길 8-8','050-4570-8607','O',NULL);
--행 52
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'중식','센트럴 차이나','경기 성남시 분당구 판교역로192번길 14-1','031-8017-8615','X',NULL);
--행 53
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'중식','왕스덕','경기 성남시 분당구 대왕판교로645번길 36','031-606-8517','X',NULL);
--행 54
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'중식','락앤웍','경기 성남시 분당구 운중로146번길 23-1','031-703-8008','X',NULL);
--행 55
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'중식','첸','경기 성남시 분당구 운중로277번길 40-7','031-8016-0555','X',NULL);
--행 56
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'중식','홍보석','경기 성남시 분당구 동판교로52번길 9-2','031-8017-0004','O',NULL);
--행 57
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'중식','미엔엔','경기 성남시 분당구 분당로53번길 19','031-703-5759','X',NULL);
--행 58
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'중식','백년각','경기 성남시 분당구 성남대로925번길 19','031-215-7339','X',NULL);
--행 59
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'중식','투고','경기 성남시 분당구 서현로180번길 26','031-701-4896','X',NULL);
--행 60
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'중식','취룡','경기 성남시 분당구 대왕판교로 307','031-719-9318','X',NULL);
--행 61
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'양식','하하호호','제주 제주시 우도면 우도해안길 532','010-2899-1365','X',NULL);
--행 62
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'양식','버거앤치즈','서울 서대문구 이화여대5길 9','02-3291-5050','X',NULL);
--행 63
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'양식','I LOVE NEW YORK PIZZA','대구광역시 달서구 상화북로 223','050-4831-3847','O',NULL);
--행 64
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'양식','빵의 정석','서울 성동구 서울숲2길 45','02-466-9609','X',NULL);
--행 65
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'양식','비스트로주라','서울 마포구 와우산로23길 18-7','02-6406-5640','X',NULL);
--행 66
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'양식','SICTAC','서울 서대문구 성산로 527','02-362-0777','O',NULL);
--행 67
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'양식','블랙스톤','서울 서대문구 명물길 32 준성빌딩 5층','02-362-7898','X',NULL);
--행 68
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'양식','give me fever','서울 마포구 연남로3길 7','010-5091-1151','X',NULL);
--행 69
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'양식','두로스피자','서울 관악구 신림로18길 5','050-7996-8622','O',NULL);
--행 70
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'양식','버거앤파스타','부산 수영구 광안로62번길 39','051-751-6631','O',NULL);
--행 71
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'양식','피자헛','경기도 성남시 수정구 태평동 6973','031-721-3140','O',NULL);
--행 72
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'양식','버거킹','경기도 성남시 분당구 삼평동 대왕판교로 660','031-724-2610','O',NULL);
--행 73
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'양식','맥도날드','경기도 성남시 분당구 삼평동 680','070-7209-0564','X',NULL);
--행 74
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'양식','PIZZA ALVOLO','경기도 수원시 영통구 하동 192-1','031-214-8495','O',NULL);
--행 75
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'양식','아웃백','경기도 수원시 권선구 권선1동 권광로 149','031-267-0911','X',NULL);
--행 76
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'양식','빕스','경기 수원시 팔달구 우만2동 90','031-216-1997','X',NULL);
--행 77
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'양식','울프강 스테이크 하우스','서울특별시 강남구 청담동 선릉로152길 21','02-556-8700','X',NULL);
--행 78
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'양식','에릭스 뉴욕 스테이크 하우스','서울특별시 서초구 양재동 215','02-2155-1636','X',NULL);
--행 79
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'양식','쏘렌토','경기도 성남시 분당구 서현1동 82-1','031-707-3919','X',NULL);
--행 80
INSERT INTO RESTAURANT (SEQ_RESTAUR_ID,RESTAUR_KIND, RESTAUR_NAME, RESTAUR_ADDRESS, RESTAUR_PHONE, RESTAUR_DELIVER, RESTAUR_POINT) VALUES (SEQ_RESTAUR_ID.NEXTVAL,'양식','돈파스타','경기도 성남시 분당구 서현1동 250-4','031-701-2155','X',NULL);







------------------------------------------    
--샘플 메뉴데이터
------------------------------------------
--행 1
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,101.0,'빈대떡',10000.0,'막걸리에 잘어울리는 빈대떡',526.0,'쌀:국내산, 빈대:국내산');
--행 2
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,101.0,'만두전골(중)',25000.0,'수요미식회에서 인정한 만두전골',722.0,'소고기:호주산,국내산');
--행 3
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,101.0,'만두전골(대)',35000.0,'수요미식회에서 인정한 만두전골',784.0,'소고기:호주산,국내산');
--행 4
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,102.0,'전복미역국',14000.0,'통영전복과 미역으로 만든 미역국',612.0,'전복, 미역: 국내산(통영)');
--행 5
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,102.0,'참문어 강된장비빔밥',16000.0,'매일 직배송되는 동해산 자연문어 비빔밥',640.0,'문어:국내(동해)');
--행 6
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,102.0,'전복무쇠솥밥(2인)',42000.0,'호통영 대표메뉴인 전복 돌솥밥',812.0,'전복:통영, 쌀:국내산');
--행 7
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,103.0,'곤드레 나물밥',7000.0,'곤드레나물로 만든 밥',418.0,'곤드레나물 : 국내산(영월)');
--행 8
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,103.0,'오징어볶음',7500.0,'고추장 베이스를 기본으로 한 오징어볶음',444.0,'오징어:국내산');
--행 9
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,103.0,'김치찜(2인)',18000.0,'직접 만든 김치로 만든 찜',658.0,'김치: 국내산');
--행 10
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,104.0,'순두부백반',8000.0,'직접 손으로 만든 순두부 백반',468.0,'콩 :국내산');
--행 11
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,104.0,'얼큰째복순두부',9000.0,'집접만든 순두부와 얼큰하게 만든 찌개',516.0,'콩:국내산, 고추가루:국내산,중국산');
--행 12
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,104.0,'모두부',12000.0,'직접 손으로 만든 모두부',570.0,'콩:국내산');
--행 13
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,105.0,'차돌박이',27000.0,'국내산 특상등급한우',742.0,'소고기:국내산');
--행 14
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,105.0,'생등심',42000.0,'국내산 특상등급한우150g',814.0,'소고기 :국내산');
--행 15
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,105.0,'안심',45000.0,'국내산 특상등급한우 150g',818.0,'소고기 : 국내산');
--행 16
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,106.0,'굴비정식',28000.0,'상급굴비와 옛날반찬과 드립니다.',750.0,'굴비:국내산');
--행 17
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,106.0,'가자미구이갈비찜정식',30000.0,'가자미구이와 한방돼지갈비',762.0,'가자미:국내산');
--행 18
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,106.0,'옛날집디럭스',35000.0,'상급굴비,떡갈비,불고기,옛날집반찬',786.0,'굴비:국내산, 소고기:국내산');
--행 19
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,107.0,'고사리육개장',8000.0,'제주고유의 전통적 국',470.0,'사골 : 국내산 육무');
--행 20
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,107.0,'몸국',8000.0,'제주고유의 전통적 국',472.0,'사골: 국내산 육무');
--행 21
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,107.0,'사골 해장국',8000.0,'할머니가 직접 만드는 해장국',474.0,'쇠고기:국내산,호주산,미국산');
--행 22
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,108.0,'주류(소주,맥주,막걸리)',4000.0,'주류',366.0,'주류:국내산');
--행 23
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,108.0,'석쇠불고기쌈밥정식',15000.0,'유기농 석쇠불고기 쌈밥정식',618.0,'돼지고기 : 국내산');
--행 24
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,108.0,'파전',15000.0,'직접 키운 파와 쪽파로 만든 파전',620.0,'쌀,돼지고기:국내산');
--행 25
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,109.0,'전주비빔밥',11000.0,'전주의 대표적 음식',560.0,'소고기:국내산');
--행 26
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,109.0,'돌솥비빔밥',11000.0,'돌솥비빔밥',562.0,'쌀:국내산');
--행 27
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,109.0,'놋그릇비빔밥',13000.0,'옛날의 비빔밥을 추억할수 있는 비빔밥',590.0,'김치배추:국내산');
--행 28
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,110.0,'불고기',30000.0,'2대 180g',764.0,'소고기: 국내산');
--행 29
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,110.0,'양념갈비',36000.0,'1인분 170g',802.0,'소고기 : 국내산');
--행 30
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,110.0,'생갈비',42000.0,'국내산한우',816.0,'소고기 :국내산');
--행 31
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,111.0,'떡갈비스테이크',3800.0,'떡갈비 페티가 들어간 떡샌드위치',358.0,'돼지고기: 국내산');
--행 32
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,111.0,'허브갈릭소시지',3800.0,'마늘소스와 소시지가 들어간 수제떡샌드위치',360.0,'떡: 국내산, 소시지: 미국산');
--행 33
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,111.0,'베이컨치즈',3800.0,'베이컨과 치즈가 들어간 수제떡샌드위치',362.0,'떡: 국내산, 베이컨: 미국산');
--행 34
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,112.0,'설렁탕',7000.0,'뜨근한 국물에 밥한공기 뚝딱',420.0,'돼지고기: 수입산');
--행 35
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,112.0,'김치찌개',7500.0,'얼큰칼칼 돼지고기가 들어간 김치찌개',446.0,'돼지고기: 국내산, 김치: 국내산');
--행 36
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,112.0,'추어탕',8000.0,'원기회복에 좋은 추어탕',476.0,'미꾸라지: 국내산');
--행 37
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,113.0,'김치찌개',6000.0,'얼큰 칼칼 김치찌개',394.0,'김치: 국내산');
--행 38
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,113.0,'삼계탕',30000.0,'몸보신에 제격인 삼계탕',766.0,'닭고기 : 국내산');
--행 39
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,113.0,'오리백숙',35000.0,'여러가지 한약재와 백숙의 만남',788.0,'오리고기: 국내산');
--행 40
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,114.0,'철판낙지볶음',8000.0,'싱싱한 낙지와 매콤한 양념의 만남',478.0,'낙지: 국내산');
--행 41
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,114.0,'세발낙지',15000.0,'싱싱한 세발낙지와 소주한잔',622.0,'낙지 : 국내산');
--행 42
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,114.0,'낙지탕',20000.0,'몸보신으로 제격인 낙지탕',678.0,'낙지: 국내산');
--행 43
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,115.0,'물냉면',5000.0,'시원한 육수의 물냉면',378.0,'면: 국내산');
--행 44
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,115.0,'비빔냉면',5500.0,'얼큰한 양념의 비빔냉면',382.0,'면: 국내산');
--행 45
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,115.0,'코다리냉면',6500.0,'쫄깃한코다리와 냉면의 만남',406.0,'코다리: 국내산');
--행 46
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,116.0,'한방 백숙',33000.0,'한방 백숙은 음식이 아니라 보약',778.0,'닭고기: 국내산');
--행 47
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,116.0,'한방 삼계탕',35000.0,'한방 삼계탕은 음식이 아니라 보약',790.0,'닭고기: 국내산');
--행 48
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,116.0,'한방 오리백숙',40000.0,'한한방 오리백숙은 음식이 아니라 보약',808.0,'오리고기: 국내산');
--행 49
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,117.0,'함흥곰보냉면',7000.0,'함흥식 곰보 냉면',422.0,'면: 국내산');
--행 50
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,117.0,'육쌈냉면',7500.0,'쫄깃한 고기와 감칠맛나는 냉면의 조화',448.0,'돼지고기: 국내산');
--행 51
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,117.0,'돈까스냉면',7500.0,'돈까스와 냉면의 만남',450.0,'돼지고기: 국내산');
--행 52
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,118.0,'양념 곰장어 석쇠구이',12000.0,'특제 양념소스와 기장산 곰장어',572.0,'곰장어: 국내산');
--행 53
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,118.0,'소금 곰장어 석쇠구이',12000.0,'천일염과 기장산 곰장어의 조화',574.0,'곰장어: 국내산');
--행 54
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,118.0,'야채 곰장어 석쇠구이',12000.0,'향긋한 야채와 함께 볶은 곰장어',576.0,'곰장어: 국내산');
--행 55
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,119.0,'공주 알밤 막걸리',4500.0,'구수한 알밤으로 정성스레 빚은 수제막걸리',370.0,'밤: 국내산');
--행 56
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,119.0,'할매 김치전',7500.0,'50년 전통 할매 김치전',452.0,'밀가루: 국내산, 김치: 국내산');
--행 57
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,119.0,'할매 파전',8000.0,'50년 전통 할매 파전',480.0,'밀가루: 국내산, 파: 국내산');
--행 58
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,120.0,'순대국밥',5500.0,'추운날 마음까지 따듯해지는 순대국밥',384.0,'돼지고기: 국내산');
--행 59
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,120.0,'선지국밥',6000.0,'철분이 듬뿍 선지국',396.0,'선지: 국내산, 돼지고기: 국내산');
--행 60
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,120.0,'설렁탕',6000.0,'24시간 푹 끓인 설렁탕',398.0,'돼지고기:국내산');
--행 61
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,121.0,'간장닭튀김',6500.0,'인기 사이드 메뉴인 짭롬한 닭튀김',408.0,'닭고기 : 브라질산');
--행 62
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,121.0,'돈까스 카레 우동',10500.0,'바삭한 돈까스를 얹은 카레 우동',552.0,'돼지고기 : 국내산');
--행 63
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,121.0,'함박 스테-끼 밥',12600.0,'육즙이 풍부한 함박 스테이크',588.0,'소고기 : 호주산');
--행 64
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,122.0,'연어회덮밥 정식',15000.0,'여성선호도 1위, 연어가 한가득',624.0,'연어 : 칠레산');
--행 65
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,122.0,'규동 정식',15000.0,'불맛 가득한 소고기 덮밥',626.0,'소고기 : 호주산');
--행 66
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,122.0,'새우튀김',17000.0,'싱싱한 새우로 만든 모둠 새우튀김',646.0,'돼직고기 : 국내산');
--행 67
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,123.0,'스시정식',20000.0,'긴자의 대표메뉴',680.0,'활어 : 국내산');
--행 68
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,123.0,'활릉전복죽',25000.0,'싱싱한 전복이 들어간 전복죽',724.0,'전복 : 국내산');
--행 69
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,123.0,'고메벤또 (특초밥)',38000.0,'특초밥이 올라간 든든한 벤또',804.0,'활어 : 국내산');
--행 70
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,124.0,'본참치',30000.0,'싱싱한 국내산 참치',768.0,'참치 : 국내산');
--행 71
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,124.0,'도원참치',39000.0,'싱싱한 국내산 참치',806.0,'참치 : 국내산');
--행 72
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,124.0,'혼골드참치',100000.0,'싱싱한 국내산 참치',828.0,'참치 : 국내산');
--행 73
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,125.0,'초밥 정식',12000.0,'스시 8p, 우동, 튀김',578.0,'활어 : 국내산');
--행 74
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,125.0,'우동 정식',12000.0,'우동, 스시4p, 튀김',580.0,'밀가루 : 국내산');
--행 75
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,125.0,'냉모밀 정식',12000.0,'모밀, 스시5p, 튀김',582.0,'밀가루 : 국내산');
--행 76
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,126.0,'생연어마요덮밥',6500.0,'담백한 생연어마요덮밥',410.0,'연어 : 페루산');
--행 77
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,126.0,'매콤참치덮밥',6500.0,'매콤한 참치덮밥',412.0,'참치 : 페루산');
--행 78
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,126.0,'생연어덮밥(사케동)',7600.0,'깔끔한 생연어덮밥',464.0,'연어 : 페루산');
--행 79
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,127.0,'반반라이스(카레,하야시)',10000.0,'두가지 맛을 느낄 수 있는 반반라이스',528.0,'쌀 : 국내산');
--행 80
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,127.0,'모츠나베',18000.0,'CORNER111 대표메뉴',660.0,'소고기 : 국내산');
--행 81
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,127.0,'오꼬노미야끼',18000.0,'일본의 맛 그대로, 오꼬노미야끼',662.0,'문어 : 호주산');
--행 82
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,128.0,'고기교자',5000.0,'곁들여먹는 사이드메뉴',380.0,'돼지고기 : 미국산');
--행 83
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,128.0,'라멘',8000.0,'돈코츠 사골 육수 라멘',482.0,'돼지고기 : 미국산');
--행 84
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,128.0,'돈가츠',8000.0,'정통 수제 돈가츠',484.0,'돼지고기 : 미국산');
--행 85
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,129.0,'코도모 스테이크 덮밥',9800.0,'일본 후쿠오카에서 상륙한 인기메뉴',524.0,'소고기 : 호주산');
--행 86
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,129.0,'삼겹살 야키우동',10800.0,'삼겹살 철판 볶음 우동',556.0,'밀가루 : 국내산');
--행 87
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,129.0,'갈릭치킨 철판정식',11800.0,'담백한 갈릭치킨 철판 정식',568.0,'닭고기 : 브라질산');
--행 88
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,130.0,'카라이 규동',9000.0,'일본식 사천 소고기 구이 덮밥',518.0,'소고기 : 호주산');
--행 89
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,130.0,'명란 크림 우동',10000.0,'수제 크림소스 + 명란마요',530.0,'명란 : 일본산');
--행 90
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,130.0,'덴푸라 동(텐동)',11000.0,'가츠동,새우,문어,치킨 모듬 튀김 덮밥',564.0,'새우 : 칠레산');
--행 91
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,131.0,'사케동',10000.0,'연어회덮밥',532.0,'연어 : 국내산');
--행 92
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,131.0,'가이센벤토',15000.0,'회 사시미 벤토',628.0,'활어 : 국내산');
--행 93
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,131.0,'스테이크벤토',15000.0,'두툼한 스테이크 덮밥',630.0,'소고기 : 칠레산');
--행 94
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,132.0,'에비 동',10000.0,'간장소스로 감칠맛이 풍부한 에비 동',534.0,'새우 : 미국산');
--행 95
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,132.0,'나가사키 짬뽕',14000.0,'얼큰한 국물이 일품인 나가사키 짬뽕',614.0,'새우 : 미국산');
--행 96
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,132.0,'유노추보스타일 고로케',17000.0,'야채, 카레맛 고로케',648.0,'밀가루 : 중국산');
--행 97
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,133.0,'눈꽃 소바',7500.0,'시원한 국물의 눈꽃 소바',454.0,'밀가루 : 국내산');
--행 98
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,133.0,'나가사끼 우동',8000.0,'대표메뉴, 나가사끼 우동',486.0,'오징어 : 중국산');
--행 99
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,133.0,'눈꽃 사라다 우동',8500.0,'새우튀김이 올라간 눈꽃 사라다 우동',500.0,'밀가루 : 국내산');
--행 100
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,134.0,'나무우동소바',8000.0,'깔끔한 국물이 일품인 대표메뉴',488.0,'밀가루 : 국내산');
--행 101
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,134.0,'카레우동',9000.0,'진한 카레맛을 느낄 수 있는 카레우동',520.0,'카레 : 인도산');
--행 102
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,134.0,'튀김우동소바',10000.0,'3가지 튀김이 어우러진 우동 소바',536.0,'밀가루 : 국내산');
--행 103
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,135.0,'오리엔탈 연어 덮밥',8900.0,'숙성된 연어에 오리엔탈 소스가 어우러진 덮밥',510.0,'연어 : 중국산');
--행 104
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,135.0,'와사비마요 쉬림프 포케',8900.0,'톡쏘는 와사비마요가 매력인 쉬림프 포케',512.0,'새우 : 호주산');
--행 105
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,135.0,'칠리마요 육회 덮밥',8900.0,'특제 수제 칠리소스를 올린 육회 덮밥',514.0,'소고기 : 국내산');
--행 106
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,136.0,'가츠동',7500.0,'일본식 간장에 양파를 조려낸 소스를 얹은 가츠동',456.0,'돼지고기 : 호주산');
--행 107
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,136.0,'가라아게동',8500.0,'일본 전통 튀김법으로 튀겨낸 가라아게',502.0,'닭고기 : 국내산');
--행 108
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,136.0,'사케동',13000.0,'생연어에 생와사비와 일본간장을 곁들은 사케동',592.0,'연어 : 칠레산');
--행 109
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,137.0,'오 세트',14900.0,'기존 정식 요리 한상',616.0,'고등어 : 국내산');
--행 110
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,137.0,'후 세트',16900.0,'샤브샤브 요리 한상',644.0,'소고기 : 호주산');
--행 111
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,137.0,'정 세트',18900.0,'미소등갈비와 카레치킨의 치즈카레퐁듀',672.0,'소고기 : 호주산');
--행 112
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,138.0,'쥬도치즈',10000.0,'참치내장을 곁들인 크림치즈',538.0,'참치 : 호주산');
--행 113
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,138.0,'타코와사비',10000.0,'쭈꾸미 와사비 절임',540.0,'쭈꾸미 : 페루산');
--행 114
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,138.0,'고노와다',10000.0,'해삼 내장 절임',542.0,'해삼 : 중국산');
--행 115
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,139.0,'오야꼬돈',7000.0,'닭튀김 간장 덮밥',424.0,'닭고기 : 국내산');
--행 116
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,139.0,'삿뽀로 미소라멘',7000.0,'돈코츠 사골 육수 라멘',426.0,'돼지고기 : 국내산');
--행 117
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,139.0,'크림카레우동(매운맛)',8000.0,'수제 크림소스 카레우동',490.0,'밀가루 : 호주산');
--행 118
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,140.0,'야끼니꾸',24000.0,'매콤소스에 숙성한 한우대창 구이',706.0,'소고기 : 국내산');
--행 119
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,140.0,'버섯모츠나베',27000.0,'미소/소유 베이스의 버섯모츠나베',744.0,'소고기 : 국내산');
--행 120
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,140.0,'어묵 모츠나베',27000.0,'미소/소유 베이스의 어묵 모츠나베',746.0,'소고기 : 국내산');
--행 121
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,141.0,'양꼬치',13000.0,'원기회복에 좋은 양꼬치',594.0,'양고기 : 뉴질랜드산');
--행 122
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,141.0,'양등갈비',20000.0,'담백한 맛이 일품인 양등갈비',682.0,'양고기 : 뉴질랜드산');
--행 123
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,141.0,'양고기 샤브샤브',45000.0,'중국식 샤브샤브',820.0,'양고기 : 뉴질랜드산');
--행 124
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,142.0,'지삼선',12000.0,'중국식 가지볶음',584.0,'가지 : 국내산');
--행 125
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,142.0,'양꼬치',13000.0,'원기회복에 좋은 양꼬치',596.0,'양고기 : 뉴질랜드산');
--행 126
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,142.0,'꿔봐로우',15000.0,'중국식 찹쌀 탕수육',632.0,'돼지고기 : 국내산');
--행 127
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,143.0,'청경채 마늘 볶음',8500.0,'청경채 마늘 볶음',504.0,'청경채 : 국내산');
--행 128
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,143.0,'게살 스프',10500.0,'게살 듬뿍 게살 스프',554.0,'게살 : 중국산');
--행 129
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,143.0,'랩 더 치킨',20500.0,'오븐에 구운 닭다리살',688.0,'닭고기 : 브라질산');
--행 130
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,144.0,'짜장면',6000.0,'일품 짜장면',400.0,'밀가루 : 미국산');
--행 131
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,144.0,'깐풍중새우',35000.0,'바삭한 통새우 튀김',792.0,'새우 : 태국산');
--행 132
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,144.0,'전가복',55000.0,'고기와 해산물이 들어간 볶음요리',822.0,'돼지고기 : 국내산');
--행 133
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,145.0,'간짜장',6000.0,'일품 간짜장',402.0,'밀가루 : 미국산');
--행 134
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,145.0,'생굴짬뽕',7000.0,'얼큰한 짬뽕',428.0,'밀가루 : 미국산');
--행 135
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,145.0,'매생이 생굴짬뽕',8000.0,'바다의 깊은 맛이 나는 짬뽕',492.0,'밀가루 : 미국산');
--행 136
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,146.0,'삼선짜장면',7000.0,'해산물이 들어간 짜장면',430.0,'밀가루 :국내산');
--행 137
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,146.0,'라조기',25000.0,'중국식 닭튀김',726.0,'닭고기 : 국내산');
--행 138
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,146.0,'삼품냉채',27500.0,'해산물 냉채',748.0,'해산물 : 중국산');
--행 139
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,147.0,'군만두',3000.0,'군만두',354.0,'밀가루 : 국내산');
--행 140
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,147.0,'새우볶음밥',7000.0,'새우볶음밥',432.0,'쌀 : 국내산');
--행 141
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,147.0,'고기 고추잡채',7000.0,'볶은 고기가 들어간 고추잡채',434.0,'돼지고기 : 국내산');
--행 142
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,148.0,'잡채밥',7500.0,'매콤한 잡채밥',458.0,'쌀 : 국내산');
--행 143
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,148.0,'볶짬면',7500.0,'볶음밥+짬뽕',460.0,'밀가루 : 국내산');
--행 144
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,148.0,'탕짜면',8000.0,'탕수육+짜장면',494.0,'돼지고기기 :국내산');
--행 145
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,149.0,'해물우동',6000.0,'시원한 해물우동',404.0,'밀가루 : 국내산');
--행 146
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,149.0,'굴짬뽕',8000.0,'시원한 굴짬뽕',496.0,'밀가루 : 국내산');
--행 147
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,149.0,'라조육',25000.0,'중국식 고추 돼지튀김',728.0,'돼지고기 : 국내산');
--행 148
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,150.0,'사천탕면',8000.0,'백짬뽕',498.0,'밀가루 : 국내산');
--행 149
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,150.0,'게살샥스핀',35000.0,'게살과 샥스핀 스프',794.0,'샥스핀 : 중국산');
--행 150
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,150.0,'송이관자',40000.0,'송이버섯관자를 볶음요리',810.0,'송이버섯 : 국내산');
--행 151
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,151.0,'낙지짬뽕',10000.0,'낙지 한마리가 들어 간 짬뽕',544.0,'낙지 : 필리핀산');
--행 152
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,151.0,'조개짬뽕',10000.0,'각종 조개가 들어 간 짬뽕',546.0,'조개 : 국내산');
--행 153
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,151.0,'삼선볶음짬뽕',15000.0,'해물이 들어간 볶음짬뽕',634.0,'해산물 : 국내산');
--행 154
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,152.0,'마파두부밥',7000.0,'마파두부밥',436.0,'두부 : 국내산');
--행 155
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,152.0,'팔보채',29000.0,'채소와 해물을 볶음요리',760.0,'해물 : 국내산');
--행 156
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,152.0,'해삼탕',55000.0,'중국의 보양음식',824.0,'해삼 : 국내산');
--행 157
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,153.0,'오리꿔바로우',17000.0,'오리 탕수육',650.0,'오리 : 국내산');
--행 158
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,153.0,'궁보새우볶음',35000.0,'고추기름 사용한 새우볶음',796.0,'새우 : 필리핀');
--행 159
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,153.0,'북경오리',85000.0,'북경식 오리 구이',826.0,'오리 : 국내산');
--행 160
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,154.0,'삼선짜장면',7000.0,'해물 짜장면',438.0,'밀가루 : 국내산');
--행 161
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,154.0,'탕수육',28000.0,'돼지고기 튀김',752.0,'돼지고기 : 국내산');
--행 162
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,154.0,'유린기',28000.0,'중국식 소스를 부은 닭튀김',754.0,'닭고기 : 국내산');
--행 163
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,155.0,'문어짬뽕',10000.0,'문어가 들어간 짬뽕',548.0,'밀가루 : 국내산');
--행 164
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,155.0,'잡탕밥',13000.0,'해산물 소스를 부어 먹는 요리',598.0,'해산물 : 국내산');
--행 165
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,155.0,'유산슬밥',13000.0,'고기와 해산물 소스를 부어 먹는 요리',600.0,'쌀 : 국내산');
--행 166
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,156.0,'굴짬뽕',9000.0,'굴이 들어간 짬뽕',522.0,'밀가루 : 국내산');
--행 167
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,156.0,'찹쌀 탕수육',25000.0,'찹쌀 탕수육',730.0,'돼지고기 : 국내산');
--행 168
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,156.0,'깐쇼새우',32000.0,'매콤한 새우튀김',776.0,'새우 : 말레이시아');
--행 169
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,157.0,'옛날 짜장',4000.0,'옛날 짜장',368.0,'밀가루 : 미국산');
--행 170
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,157.0,'간짜장',5500.0,'간짜장',386.0,'밀가루 : 미국산');
--행 171
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,157.0,'누룽지순두부짬뽕',7000.0,'누룽지+순두부+짬뽕',440.0,'밀가루 : 미국산');
--행 172
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,158.0,'후난식 볶음밥',6900.0,'후난식 볶음밥',414.0,'쌀 : 국내산');
--행 173
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,158.0,'백년각 짬뽕',7900.0,'본점만의 스페셜 짬뽕',466.0,'밀가루 : 국내산');
--행 174
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,158.0,'눈꽃탕수육',20000.0,'한입에 넣을 수 있는 탕수육',684.0,'돼지고기 : 국내산');
--행 175
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,159.0,'우육탕면',10000.0,'돼지고기 육수 베이스인 국수',550.0,'밀가루 : 국내산');
--행 176
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,159.0,'차우멘치킨',12000.0,'중국식 닭 튀김',586.0,'닭고기 : 국내산');
--행 177
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,159.0,'양장피',25000.0,'겨자소스에 각종 채소를 비벼 먹는 음식',732.0,'채소 : 국내산');
--행 178
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,160.0,'짜장밥',5500.0,'짜장밥밥',388.0,'밀가루 : 국내산산');
--행 179
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,160.0,'차돌순두부짬뽕',8500.0,'고기육수 짬뽕',506.0,'밀가루 : 국내산');
--행 180
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,160.0,'사천탕수육',16000.0,'사천식 탕수육',642.0,'돼지고기 : 국내산');
--행 181
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,161.0,'구좌마늘 흑돼지버거',13000.0,'마늘과 흑돼지 페티로 만들어진 수제햄버거',602.0,'흑돼지,마늘 :제주산');
--행 182
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,161.0,'우도땅콩 흑돼지버거',13000.0,'땅콩소스와 흑돼지 페티로 만들어진 수제햄버거',604.0,'흑돼지,땅콩 :제주산');
--행 183
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,161.0,'제주 딱새우버거',13000.0,'제주딱새우로 만들어진 수제햄버거',606.0,'흑돼지,새우 :제주산');
--행 184
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,162.0,'붹붹버거',5500.0,'더블 불고기패티버거',390.0,'소고기 : 미국산');
--행 185
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,162.0,'삼붹버거',7500.0,'트리플 불고기패티버거',462.0,'소고기 : 미국산');
--행 186
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,162.0,'칠리치즈나쵸',8500.0,'NachoChip,Cheese,Meat',508.0,'소고기 : 미국산');
--행 187
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,163.0,'포테이토베이컨피자',24000.0,'감자와 베이컨 등 토핑이 많은 피자',708.0,'감자: 미국산');
--행 188
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,163.0,'소불고기피자',24000.0,'소불고기와 치즈로 만들어진 피자',710.0,'소고기: 호주산');
--행 189
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,163.0,'돼지직화불고기피자',24000.0,'돼지직화불고기가 들어간 피자',712.0,'돼지고기 : 미국산');
--행 190
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,164.0,'크로와상',2800.0,'밀가루와 버터로 반죽을 빚은 초승달모양의 빵',352.0,'밀가루: 국내산');
--행 191
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,164.0,'빨미까레',3000.0,'초콜릿을 묻힌 파이',356.0,'밀가루: 국내산');
--행 192
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,164.0,'앙프레즐',3800.0,'앙버터와 팥이 들어간 빵',364.0,'밀가루: 국내산');
--행 193
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,165.0,'스테이크 크림 파스타',13000.0,'스테이크와 청양 크림파스타',608.0,'소고기: 미국산');
--행 194
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,165.0,'부채살 스테이크 정식',15000.0,'M: 150g, L:200g (샐러드파스타,국,밥 포함)',636.0,'소고기: 미국산');
--행 195
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,165.0,'살치살 스테이크 정식',17000.0,'M: 150g, L:200g (샐러드파스타,국,밥 포함)',652.0,'소고기: 미국산');
--행 196
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,166.0,'클래식 까르보나라',11000.0,'이태리전통 레시피로 만든 크림파스타',566.0,'돼지고기: 수입산');
--행 197
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,166.0,'루꼴라 마르게리따',17000.0,'바질 페스트로 맛을 낸 담백한 토마토 피자',654.0,'돼지고기: 수입산');
--행 198
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,166.0,'안심스테이크',25000.0,'안심 스테이크에 샐러드를 곁들인 요리',734.0,'소고기: 호주산');
--행 199
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,167.0,'블랙 부채살 스테이크',17000.0,'감칠맛이 좋은 부채살 스테이크',656.0,'소고기: 미국산');
--행 200
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,167.0,'단호박 크림 파스타',18000.0,'통단호박에 치즈로 맛을 낸 화이트크림파스타',664.0,'소고기: 미국산');
--행 201
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,167.0,'블랙 갈비살 스테이크',19000.0,'쫀득한 질감의 갈비살 스테이크',674.0,'소고기: 미국산');
--행 202
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,168.0,'초리조 크림 뇨끼',19000.0,'초리조와 버섯을 넣고 만든 크림소스 뇨끼',676.0,'감자: 국내산');
--행 203
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,168.0,'비스크로제 파스타',20000.0,'새우와 새우껍질을 볶아만든 크림 파스타',686.0,'새우: 수입산');
--행 204
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,168.0,'오리가슴살 스테이크',22000.0,'당근,오렌지 소스로 브라인한 스테이크',696.0,'오리: 국내산');
--행 205
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,169.0,'스노우골드',22000.0,'바베큐/불닭/고구마 맛 피자',698.0,'소고기: 호주산, 돼지고기: 미국산');
--행 206
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,169.0,'포테이토골드',25000.0,'감자가 들어간 피자',736.0,'돼지고기: 미국산');
--행 207
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,169.0,'쉬림프골드',26000.0,'새우가 들어간 피자',740.0,'소고기: 호주산, 돼지고기: 미국산');
--행 208
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,170.0,'치즈버거',7300.0,'소고기 페티와 슬라이스 치즈 햄버거',442.0,'소고기: 호주산');
--행 209
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,170.0,'치킨 크림 파스타',10900.0,'치킨,양파,마늘이 들어간 크림파스타',558.0,'닭고기: 국내산');
--행 210
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,170.0,'고르곤졸라 피자',13900.0,'고르곤졸라 치즈와 모짜렐라 치즈 피자',610.0,'치즈: 국내산, 이태리산');
--행 211
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,171.0,'불고기 피자',34000.0,'불고기가 드렁간 피자',780.0,'밀가루 : 중국산');
--행 212
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,171.0,'페퍼로니 피자',31000.0,'페퍼로니만 들어가 담백하다',774.0,'밀가루 : 중국산');
--행 213
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,171.0,'치즈 피자',30000.0,'치즈만 들어가 짜지만 맛있다',770.0,'밀가루 : 중국산');
--행 214
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,172.0,'더블오리지널치즈버거',6900.0,'치즈가 맛있다 치즈가 두배!',416.0,'소고기 : 호주산');
--행 215
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,172.0,'와사비크랩버거',4500.0,'와사비의 톡쏘는 향이 게살이 들어간 버거킹 리얼 씨푸드버거',372.0,'크랩 : 하와이산');
--행 216
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,172.0,'붉은대게와퍼세트',5500.0,'부드러운 국내산 붉은대게살 패티와 100% 순쇠고기 패티버거',392.0,'대게 : 싱가폴산');
--행 217
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,173.0,'상하이스파이시치킨버거',4800.0,'상하이의 매콤함이 그대로 살아있는 치킨버거',376.0,'닭고기 : 브라질산');
--행 218
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,173.0,'불고기버거',2500.0,'불고기 패티와 함께하는 버거',350.0,'소고기 : 호주산');
--행 219
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,173.0,'빅맥',4500.0,'패티 두개 큰 햄버거',374.0,'소고기 : 호주산');
--행 220
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,174.0,'단호박피자',21000.0,'단호박 죽 맛나는 피자 웰빙',690.0,'단호박 : 국내산');
--행 221
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,174.0,'핫스파이시치킨피자',21000.0,'매운 치킨과 할라피뇨의 만남 매콤 피자',692.0,'닭고기 : 브라질산');
--행 222
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,174.0,'고구마피자',21000.0,'고구마를 두른 웰빙 피자',694.0,'고구마 : 국내산');
--행 223
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,175.0,'토마호크스테이크',35000.0,'토마호크를 닮은 뉴욕식 스테이크',798.0,'소고기 : 호주산');
--행 224
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,175.0,'립아이',28000.0,'갈비대에 소스를 바른 립아이',756.0,'소고기 : 호주산');
--행 225
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,175.0,'투움바파스타',24000.0,'투움바 스타일 파스타',714.0,'밀가루 : 국내산');
--행 226
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,176.0,'자스민 폭립',18800.0,'쟈스민향으로 풍미를 더한 부드러운 폭립',670.0,'돼지고기 : 독일산');
--행 227
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,176.0,'빕스 뉴욕 스테이크',15800.0,'허브버터에 트러플 플레이버를 더한 포테이토, 스테이크',638.0,'소고기 : 호주산');
--행 228
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,176.0,'플람베 스테이크',25200.0,'그라나파다노 치즈와 구운새우가 들어간 스테이크',738.0,'소고기 : 호주산');
--행 229
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,177.0,'FILET MIGNON',30800.0,'프라임등급 안심 스테이크',772.0,'소고기 : 호주산');
--행 230
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,177.0,'울프강 크랩 케익',28900.0,'킹크랩을 주 재료로 한 해산물 케이크',758.0,'킹크랩 : 미국산');
--행 231
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,177.0,'점보 새우 칵테일',34600.0,'칵테일 새우가 가미된 뉴욕 스타일 스테이크',782.0,'소고기 : 호주산');
--행 232
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,178.0,'티본스테이크',35000.0,'T자모양의 스테이크 뉴욕스타일',800.0,'소고기 : 국내산');
--행 233
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,178.0,'비프데리야키스테이크',24000.0,'데리야키 소스가 가미된 스테이크',716.0,'소고기 : 국내산');
--행 234
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,178.0,'통안심새우스테이크',24000.0,'통 안심과 새우가 조화된 스테이크',718.0,'소고기 : 국내산');
--행 235
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,179.0,'모시 크램차우더 스파게티',18000.0,'후레시한 모시조개와 크림의 조화',666.0,'밀가루 : 국내산');
--행 236
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,179.0,'아라고스타 로제 스파게티',23000.0,'가재살 새우살 크림이 조화된 스파게티',700.0,'밀가루 : 국내산');
--행 237
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,179.0,'오징어먹물고르곤졸라피자',24000.0,'웰빙 먹물도우와 고르곤졸라 피자의 조화',720.0,'밀가루 : 중국산');
--행 238
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,180.0,'게살파스타',23000.0,'홍게살과 파스타의 조화',702.0,'홍게 : 국내산');
--행 239
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,180.0,'루꼴라스파게티',23000.0,'신선한 물소 치즈가 들어간 모던한맛',704.0,'치즈 : 국내산');
--행 240
INSERT INTO MENU (SEQ_MENU_ID,SEQ_RESTAUR_ID, MENU_NAME, MENU_PRICE, MENU_DESC, MENU_KCAL, MENU_SOURCE) VALUES (SEQ_MENU_ID.NEXTVAL,180.0,'마르게리타',18000.0,'나폴리피자의 대명사',668.0,'밀가루 : 중국산');



------------------------------------------    
--샘플 회원데이터
--데이터 임포트하세요! 왼쪽 메뉴에서
------------------------------------------


select * from restaurant order by seq_restaur_id;
select * from menu order by seq_menu_id;
select * from member;